Repository Link-MIND/TOASTER-iOS, pull requests merged in 2024-10, with the labels that each got.

#210 [Chore] #209 - 사파리 외에 다른 앱에서도 Share Extension 대응
  ToasterShareExtension/Info.plist
  ToasterShareExtension/ShareViewController.swift
Labels: 🔧 Chore, 🐻‍❄️ 민재

#211 [Feat] #208 - 웹뷰 네비바 툴바 수정사항 반영
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_read.imageset/ic_read.svg
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_share.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_share.imageset/ic_share.svg
  TOASTER-iOS/Present/LinkWeb/View/LinkWebNavigationView.swift
  TOASTER-iOS/Present/LinkWeb/View/LinkWebToolBarView.swift
  TOASTER-iOS/Present/LinkWeb/ViewController/LinkWebViewController.swift
Labels: ✨ Feat, 🐻‍❄️ 민재

#212 [Feat] #207 - MyPage, Setting 합치기
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Present/Mypage/MypageViewController.swift
  TOASTER-iOS/Present/Mypage/View/MypageAlertView.swift
  TOASTER-iOS/Present/Setting/Model/MypageUserModel.swift
  TOASTER-iOS/Present/Setting/View/Cell/SettingTableViewCell.swift
  TOASTER-iOS/Present/Setting/View/MypageHeaderView.swift
  TOASTER-iOS/Present/Setting/View/SettingView.swift
  TOASTER-iOS/Present/Setting/View/SettingViewController.swift
  TOASTER-iOS/Present/TabBar/TabBarItem.swift
Labels: ✨ Feat, 🩷 가현

#213 [Feat] #205 - ShareExtension UI 변경 및 MVVM 으로 리펙토링
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Extensions/Combine+/Publisher+UIButton.swift
  ToasterShareExtension/ShareViewController.swift
  ToasterShareExtension/ShareViewModel.swift
Labels: ✨ Feat, ♻️ Refactor, 🚗 준혁

#216 [Feat] #214 - 링크 저장 시 중복 저장 막기 & 로딩 애니메이션 추가
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Components/ToasterLoadingView/ToasterLoadingView.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UIButton+.swift
  TOASTER-iOS/Present/AddLink/SelectClip/View/SelectClipViewController.swift
  ToasterShareExtension/ShareViewController.swift
Labels: ✨ Feat, 🐻‍❄️ 민재

#221 [Feat] #215 - 검색기능 TabBar 이동 및 연결
  TOASTER-iOS/Global/Consts/StringLiterals.swift
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_search_24.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_search_24.imageset/ic_search_24.svg
  TOASTER-iOS/Present/Clip/View/ClipViewController.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipCollectionHeaderView.swift
  TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/Component/CompositioinalFactory.swift
  TOASTER-iOS/Present/Home/View/HomeViewController.swift
  TOASTER-iOS/Present/Search/View/SearchViewController.swift
  TOASTER-iOS/Present/TabBar/TabBarItem.swift
Labels: ✨ Feat, 🩷 가현
