Repository Link-MIND/TOASTER-iOS, pull requests merged in 2024-11, with the labels that each got.

#224 [Feat] #217 - 다른 클립으로 링크 이동 및 UI 구현
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Components/ToasterBottomSheet/ToasterBottomSheetViewController.swift
  TOASTER-iOS/Network/Toaster/DTO/Request/PatchChangeCategoryRequestDTO.swift
  TOASTER-iOS/Network/Toaster/DTO/Response/PatchChangeCategoryResponseDTO.swift
  TOASTER-iOS/Network/Toaster/ToasterAPIService.swift
  TOASTER-iOS/Network/Toaster/ToasterTargetType.swift
  TOASTER-iOS/Present/DetailClip/View/Component/ChangeClipBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/EditLinkBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/LinkOptionBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/ChangeClipViewModel.swift
  TOASTER-iOS/Present/RemindAdd/ClipAdd/View/Cell/RemindSelectClipCollectionViewCell.swift
  ToasterShareExtension/ShareViewController.swift
Labels: ✨ Feat, 🐛 Fix, 🚗 준혁

#225 [Feat] #223 - Home 최근 저장한 링크
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Network/Toaster/DTO/Response/GetRecentLinkResponseDTO.swift
  TOASTER-iOS/Network/Toaster/ToasterAPIService.swift
  TOASTER-iOS/Network/Toaster/ToasterTargetType.swift
  TOASTER-iOS/Present/DetailClip/View/Cell/DetailClipListCollectionViewCell.swift
  TOASTER-iOS/Present/Home/Model/RecentLinkModel.swift
  TOASTER-iOS/Present/Home/View/Cell/HomeHeaderCollectionView.swift
  TOASTER-iOS/Present/Home/View/Cell/UserClipEmptyCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/Component/CompositioinalFactory.swift
  TOASTER-iOS/Present/Home/View/HomeViewController.swift
  TOASTER-iOS/Present/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feat, 🩷 가현

#227 [Feat] #226 - 클립 이동 제한 로직 및 버튼 액션 추가
  TOASTER-iOS/Present/DetailClip/View/Component/ChangeClipBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/ChangeClipViewModel.swift
Labels: ✨ Feat, 🚗 준혁

#228 [Feat] #220 - ToolTip 재사용 코드 구현 & 프로젝트 적용
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Components/ToasterLoadingView/ToasterLoadingView.swift
  TOASTER-iOS/Global/Components/ToasterTipView/TipPathView.swift
  TOASTER-iOS/Global/Components/ToasterTipView/TipUserDefaults.swift
  TOASTER-iOS/Global/Components/ToasterTipView/ToasterTipView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/LinkOptionBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/Home/View/HomeViewController.swift
  TOASTER-iOS/Present/LinkWeb/View/LinkWebNavigationView.swift
  TOASTER-iOS/Present/LinkWeb/View/LinkWebToolBarView.swift
  TOASTER-iOS/Present/LinkWeb/ViewController/LinkWebViewController.swift
Labels: ✨ Feat, ⚙️ Setting, 🐻‍❄️ 민재

#230 [Fix] #229 - 복사, 붙여넣기 허용 알럿 관련 로직 수정
  TOASTER-iOS/Application/SceneDelegate.swift
  TOASTER-iOS/Present/AddLink/LinkEmbed/View/AddLinkViewController.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재

#232 [Fix] #231 - 3차 스프린트 최종 QA 내용 반영
  TOASTER-iOS/Present/DetailClip/View/Component/ChangeClipBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/ChangeClipViewModel.swift
  TOASTER-iOS/Present/RemindAdd/ClipAdd/View/Cell/RemindSelectClipCollectionViewCell.swift
  ToasterShareExtension/ShareViewController.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재
