Repository Link-MIND/TOASTER-iOS, pull requests merged in 2024-05, with the labels that each got.

#184 [Feat] #180 - 강제 업데이트 Alert 구현
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Application/SceneDelegate.swift
  TOASTER-iOS/Present/UpdateAlert/UpdateAlertManager.swift
  TOASTER-iOS/Present/UpdateAlert/UpdateAlertType.swift
Labels: ✨ Feat, 🐻‍❄️ 민재

#185 [Feat] #179 - 이중 바텀시트 및 링크 제목 수정 구현
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TOASTER-iOS.xcodeproj/xcshareddata/xcschemes/TOASTER-iOS.xcscheme
  TOASTER-iOS/Global/Consts/StringLiterals.swift
  TOASTER-iOS/Network/Toaster/DTO/Request/PatchEditLinkTitleRequestDTO.swift
  TOASTER-iOS/Network/Toaster/DTO/Response/PatchEditLinkTitleResponseDTO.swift
  TOASTER-iOS/Network/Toaster/ToasterAPIService.swift
  TOASTER-iOS/Network/Toaster/ToasterTargetType.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DeleteLinkBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DetailEditLinkBottomSheet.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DetailEditLinkBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/DetailClipPropertyType.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/DetailClipViewModel.swift
  TOASTER-iOS/TOASTER-iOS.entitlements
  ToasterShareExtension/ShareViewController.swift
Labels: ✨ Feat, 🩷 가현

#188 [Fix] #187 - 바텀 시트 keyboardHeight 로직변경
  TOASTER-iOS/Global/Components/ToasterBottomSheet/ToasterBottomSheetViewController.swift
Labels: 🐛 Fix, 🚨 review required 🚨, 🚗 준혁

#190 [Fix] #189 - "붙여넣기 허용 안함" 최초 1회 클릭 이후, 동일 알럿 더이상 노출되지 않도록 설정
  TOASTER-iOS/Application/SceneDelegate.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재
