Repository Link-MIND/TOASTER-iOS, pull requests merged in 2024-02, with the labels that each got.

#152 [Fix] #149 - 클립 편집 드래그앤드랍 버그 수정
  TOASTER-iOS/Present/AddLink/View/AddLinkView.swift
  TOASTER-iOS/Present/EditClip/ViewController/EditClipViewController.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재

#155 [Design] #154 - 클립 추가 버튼 테두리 추가
  TOASTER-iOS/Present/Home/View/Cell/UserClipEmptyCollectionViewCell.swift
Labels: 💄 Design, 🩷 가현

#157 [Refactor] #153 - 클립, 클립상세, 클립수정 MVVM 구조로 리팩토링
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Present/Clip/View/Cell/ClipListCollectionViewCell.swift
  TOASTER-iOS/Present/Clip/View/ClipViewController.swift
  TOASTER-iOS/Present/Clip/View/Component/AddClipBottomSheetView.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipCollectionHeaderView.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipEmptyView.swift
  TOASTER-iOS/Present/Clip/ViewModel/ClipViewModel.swift
  TOASTER-iOS/Present/DetailClip/View/Cell/DetailClipListCollectionViewCell.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DeleteLinkBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DetailClipEmptyView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DetailClipSegmentedControlView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/DetailClipPropertyType.swift
  TOASTER-iOS/Present/DetailClip/ViewModel/DetailClipViewModel.swift
  TOASTER-iOS/Present/EditClip/View/EditClipViewController.swift
  TOASTER-iOS/Present/EditClip/ViewModel/EditClipViewModel.swift
  TOASTER-iOS/Present/Home/HomeViewController.swift
  TOASTER-iOS/Present/LinkWeb/ViewController/LinkWebViewController.swift
Labels: ♻️ Refactor, 🐻‍❄️ 민재

#159 [Fix] # 156 - 2차 QA 반영
  TOASTER-iOS/Global/Consts/ImageLiterals.swift
  TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/Cell/WeeklyRecommendCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/CompositioinalFactory.swift
  TOASTER-iOS/Present/Home/View/Footer/HomeFooterCollectionView.swift
Labels: 🐛 Fix, 🔧 Chore, 🩷 가현

#160 [Fix] #158 - 3차 QA 작업 (웹뷰 아이콘, 서치바, 영문 검색)
  TOASTER-iOS/Global/Consts/ImageLiterals.swift
  TOASTER-iOS/Global/Extensions/UILabel+.swift
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_arrow2_back_24.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_arrow2_back_24.imageset/ic_arrow2_24.svg
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_arrow2_forward_24.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_arrow2_forward_24.imageset/ic_arrow2_24.svg
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_read.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_24/ic_read.imageset/ic_read.svg
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Image/search_bar.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Image/search_bar.imageset/search_bar.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Image/search_bar.imageset/search_bar@2x.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Image/search_bar.imageset/search_bar@3x.png
  TOASTER-iOS/Present/Clip/View/ClipViewController.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipCollectionHeaderView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/CompositioinalFactory.swift
  TOASTER-iOS/Present/Search/View/SearchViewController.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재

#163 [Fix] #162 - 링크 저장 텍스트 필드 사이즈 조정
  TOASTER-iOS/Present/AddLink/View/AddLinkView.swift
Labels: 🐛 Fix, 🩷 가현

#167 [Fix] #166 - 2차 QA: 클립 디테일, 미트볼, 바텀시트 색상 변경
  TOASTER-iOS/Present/DetailClip/View/Component/DeleteLinkBottomSheetView.swift
Labels: 🐛 Fix, 🐻‍❄️ 민재

#171 [Feat] #170 - 네트워크 연결 오류 알럿 추가
  TOASTER-iOS/Network/Base/MoyaPlugin.swift
Labels: ✨ Feat, 🐻‍❄️ 민재

#173 [Refactor] #172 - Image Assets 관리 방법 변경
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Components/ToasterBottomSheet/ToasterBottomSheetViewController.swift
  TOASTER-iOS/Global/Components/ToasterNavigationController/ToasterNavigationController.swift
  TOASTER-iOS/Global/Components/ToasterToastMessage/ToastStatus.swift
  TOASTER-iOS/Global/Consts/ImageLiterals.swift
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_alert_18_white.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_alert_18_white.imageset/ic_alert_18_white.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_alert_18_white.imageset/ic_alert_18_white@2x.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_alert_18_white.imageset/ic_alert_18_white@3x.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_check_18_white.imageset/Contents.json
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_check_18_white.imageset/ic_check_18_white.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_check_18_white.imageset/ic_check_18_white@2x.png
  TOASTER-iOS/Global/Resources/Assets/Assets.xcassets/Icons_18/ic_check_18_white.imageset/ic_check_18_white@3x.png
  TOASTER-iOS/Present/AddLink/AddLinkViewController.swift
  TOASTER-iOS/Present/AddLink/SelectClip/View/SelectClipHeaderView.swift
  TOASTER-iOS/Present/AddLink/SelectClip/ViewController/SelectClipViewController.swift
  TOASTER-iOS/Present/AddLink/View/AddLinkView.swift
  TOASTER-iOS/Present/Clip/View/Cell/ClipListCollectionViewCell.swift
  TOASTER-iOS/Present/Clip/View/ClipViewController.swift
  TOASTER-iOS/Present/Clip/View/Component/AddClipBottomSheetView.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipCollectionHeaderView.swift
  TOASTER-iOS/Present/Clip/View/Component/ClipEmptyView.swift
  TOASTER-iOS/Present/DetailClip/View/Cell/DetailClipListCollectionViewCell.swift
  TOASTER-iOS/Present/DetailClip/View/Component/DetailClipEmptyView.swift
  TOASTER-iOS/Present/EditClip/View/EditClipCollectionViewCell.swift
  TOASTER-iOS/Present/EditClip/View/EditClipViewController.swift
  TOASTER-iOS/Present/Home/HomeViewController.swift
  TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/Cell/UserClipCollectionViewCell.swift
  TOASTER-iOS/Present/Home/View/Cell/UserClipEmptyCollectionViewCell.swift
  TOASTER-iOS/Present/LinkWeb/View/LinkWebNavigationView.swift
  TOASTER-iOS/Present/LinkWeb/ViewController/LinkWebViewController.swift
  TOASTER-iOS/Present/Login/SocialLoginType.swift
  TOASTER-iOS/Present/Mypage/MypageViewController.swift
  TOASTER-iOS/Present/Mypage/View/MypageAlertView.swift
  TOASTER-iOS/Present/Mypage/View/MypageHeaderView.swift
  TOASTER-iOS/Present/Remind/View/Cell/CompleteTimerCollectionViewCell.swift
  TOASTER-iOS/Present/Remind/View/Cell/WaitTimerCollectionViewCell.swift
  TOASTER-iOS/Present/Remind/View/Component/AlarmOffStateButton.swift
  TOASTER-iOS/Present/Remind/View/Component/RemindAlarmOffView.swift
  TOASTER-iOS/Present/Remind/View/Component/RemindTimerEmptyView.swift
  TOASTER-iOS/Present/Remind/View/RemindViewController.swift
  TOASTER-iOS/Present/RemindAdd/ClipAdd/View/Cell/RemindSelectClipCollectionViewCell.swift
  TOASTER-iOS/Present/RemindAdd/ClipAdd/View/RemindSelectClipViewController.swift
  TOASTER-iOS/Present/RemindAdd/TimerAdd/RemindTimerAddViewController.swift
  TOASTER-iOS/Present/RemindAdd/TimerAdd/View/Cell/TimerRepeatCollectionViewCell.swift
  TOASTER-iOS/Present/Search/View/SearchEmptyResultView.swift
  TOASTER-iOS/Present/Search/View/SearchViewController.swift
  TOASTER-iOS/Present/Setting/SettingViewController.swift
  TOASTER-iOS/Present/TabBar/TabBarItem.swift
Labels: ♻️ Refactor, 🚗 준혁
