Repository Link-MIND/TOASTER-iOS, pull requests merged in 2024-09, with the labels that each got.

#194 [Feat] #193 - Sheet UISheetPresentationController로 로직 변경
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Components/ToasterBottomSheet/ToasterBottomSheetViewController.swift
  TOASTER-iOS/Present/AddLink/SelectClip/View/SelectClipViewController.swift
  TOASTER-iOS/Present/Clip/View/ClipViewController.swift
  TOASTER-iOS/Present/Clip/View/Component/AddClipBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/Component/EditLinkBottomSheetView.swift
  TOASTER-iOS/Present/DetailClip/View/DetailClipViewController.swift
  TOASTER-iOS/Present/EditClip/View/EditClipViewController.swift
  TOASTER-iOS/Present/Home/View/HomeViewController.swift
  TOASTER-iOS/Present/Remind/View/RemindViewController.swift
  TOASTER-iOS/Present/RemindAdd/TimerAdd/RemindTimerAddViewController.swift
Labels: ✨ Feat, 🐛 Fix, 🐻‍❄️ 민재

#203 [Feat] #202 - 앱 최초 진입 시 설문조사 팝업 로직 구현
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Application/SceneDelegate.swift
  TOASTER-iOS/Global/Components/ToasterPopup/ToasterPopupViewController.swift
  TOASTER-iOS/Global/Extensions/UIViewController+.swift
  TOASTER-iOS/Network/Base/BaseTargetType.swift
  TOASTER-iOS/Network/Base/NetworkService.swift
  TOASTER-iOS/Network/Popup/DTO/GetPopupInfoResponseDTO.swift
  TOASTER-iOS/Network/Popup/DTO/PatchPopupHiddenRequestDTO.swift
  TOASTER-iOS/Network/Popup/DTO/PatchPopupHiddenResponseDTO.swift
  TOASTER-iOS/Network/Popup/PopupAPIService.swift
  TOASTER-iOS/Network/Popup/PopupTargetType.swift
  TOASTER-iOS/Present/Home/Model/PopupInfoModel.swift
  TOASTER-iOS/Present/Home/View/HomeViewController.swift
  TOASTER-iOS/Present/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feat, 🐻‍❄️ 민재

#204 [Refactor] #201 - AddLink MVVM 구조로 변경
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Protocols/ViewModelType.swift
  TOASTER-iOS/Present/AddLink/LinkEmbed/View/AddLinkView.swift
  TOASTER-iOS/Present/AddLink/LinkEmbed/View/AddLinkViewController.swift
  TOASTER-iOS/Present/AddLink/LinkEmbed/ViewModel/AddLinkViewModel.swift
Labels: ♻️ Refactor, 🩷 가현

#206 [Refactor] #195 - LinkWebVC MVVM 구조 변경 & Combine 사용 기초 세팅
  TOASTER-iOS.xcodeproj/project.pbxproj
  TOASTER-iOS/Global/Extensions/Combine+/CancelBag.swift
  TOASTER-iOS/Global/Extensions/Combine+/Publisher+Driver.swift
  TOASTER-iOS/Global/Extensions/Combine+/Publisher+UIBarButtonItem.swift
  TOASTER-iOS/Global/Extensions/Combine+/Publisher+UIControl.swift
  TOASTER-iOS/Global/Extensions/Combine+/Publisher+UIGesture.swift
  TOASTER-iOS/Global/Extensions/Foundation+/NSObject+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UIColor+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UILabel+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UIStackView+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UITextField+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UIView+.swift
  TOASTER-iOS/Global/Extensions/UIKit+/UIViewController+.swift
  TOASTER-iOS/Global/Protocols/ViewModelType.swift
  TOASTER-iOS/Network/Base/NetworkResult.swift
  TOASTER-iOS/Present/LinkWeb/View/LinkWebToolBarView.swift
  TOASTER-iOS/Present/LinkWeb/ViewController/LinkWebViewController.swift
  TOASTER-iOS/Present/LinkWeb/ViewModel/LinkWebViewModel.swift
Labels: ♻️ Refactor, 🐻‍❄️ 민재
